name: Chartink Jyoti Budhiya 15M Alerts

on:
  schedule:
    # Schedule runs Monday to Friday only
    # First run of the day: 09:15 AM IST -> 03:45 UTC
    - cron: '45 3 * * 1-5'
    
    # Subseqent runs every 15 minutes: 09:30 AM to 03:15 PM IST -> 04:00 UTC to 09:45 UTC
    - cron: '*/15 4-9 * * 1-5'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  run-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache-dependency-path: '' # No dependencies to cache

      - name: Run Jyoti Budhiya Script
        env:
          # Reads from GitHub Repository Secrets
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python screener_alert_jyoti_budhiya_15minutes.py
